import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core'

// better-auth tables, generated by `pnpm auth:schema`
export * from './auth-schema'

/** Key/value settings: mcp_path_secret, base_url, allow_dcr, allowed_cidrs, ... */
export const setting = sqliteTable('setting', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
})

/** One row per configured connector (id = connector type for now). */
export const connector = sqliteTable('connector', {
  id: text('id').primaryKey(),
  type: text('type').notNull(),
  name: text('name').notNull(),
  baseUrl: text('base_url'),
  /** JSON of the config; fields marked secret() are encrypted individually (lib/crypto.ts) */
  configEnc: text('config_enc').notNull(),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
  /** JSON array of tool names switched off in the admin panel */
  disabledTools: text('disabled_tools', { mode: 'json' }).$type<string[]>().notNull().default([]),
  lastCheckAt: integer('last_check_at', { mode: 'timestamp_ms' }),
  lastCheckOk: integer('last_check_ok', { mode: 'boolean' }),
  lastCheckNote: text('last_check_note'),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
})

/** result_id cache for search results: the hub keeps links, Claude only sees the id. */
export const searchResult = sqliteTable('search_result', {
  id: text('id').primaryKey(),
  connectorId: text('connector_id').notNull(),
  payloadJson: text('payload_json').notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
})

/** HTML prototypes; files live in /data/prototypes/{id}/v{version}.html */
export const prototype = sqliteTable('prototype', {
  id: text('id').primaryKey(),
  slug: text('slug').notNull().unique(),
  title: text('title').notNull(),
  pinHash: text('pin_hash'),
  /** Bumped on every pin change: invalidates access cookies */
  pinVersion: integer('pin_version').notNull().default(0),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }),
  sizeBytes: integer('size_bytes').notNull(),
  version: integer('version').notNull().default(1),
  views: integer('views').notNull().default(0),
  lastViewedAt: integer('last_viewed_at', { mode: 'timestamp_ms' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
})
