import { sqliteTable, text } from 'drizzle-orm/sqlite-core'

// better-auth tables, generated by `pnpm auth:schema`
export * from './auth-schema'

/** Key/value settings: mcp_path_secret, base_url, allow_dcr, allowed_cidrs, ... */
export const setting = sqliteTable('setting', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
})
