import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core'

// better-auth tables, generated by `pnpm auth:schema`
export * from './auth-schema'

/** Key/value settings: mcp_path_secret, base_url, allow_dcr, allowed_cidrs, ... */
export const setting = sqliteTable('setting', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
})

/** One row per configured connector (id = connector type for now). */
export const connector = sqliteTable('connector', {
  id: text('id').primaryKey(),
  type: text('type').notNull(),
  name: text('name').notNull(),
  baseUrl: text('base_url'),
  /** JSON of the config; fields marked secret() are encrypted individually (lib/crypto.ts) */
  configEnc: text('config_enc').notNull(),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
  /** JSON array of tool names switched off in the admin panel */
  disabledTools: text('disabled_tools', { mode: 'json' }).$type<string[]>().notNull().default([]),
  lastCheckAt: integer('last_check_at', { mode: 'timestamp_ms' }),
  lastCheckOk: integer('last_check_ok', { mode: 'boolean' }),
  lastCheckNote: text('last_check_note'),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
})

/** result_id cache for search results: the hub keeps links, Claude only sees the id. */
export const searchResult = sqliteTable('search_result', {
  id: text('id').primaryKey(),
  connectorId: text('connector_id').notNull(),
  payloadJson: text('payload_json').notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
})
